package com.apadanah.crypto_news.business.domain.model.main

data class SourceFilter(
    val value: String,
    val name: String,
)

val SOURCE_FILTER_LIST = listOf<SourceFilter>(
    SourceFilter("Altcoin+Buzz", "Altcoin Buzz"),
    SourceFilter("AMBCrypto", "AMBCrypto"),
    SourceFilter("BeInCrypto", "BeInCrypto"),
    SourceFilter("Benzinga", "Benzinga"),
    SourceFilter("Bitcoin", "Bitcoin"),
    SourceFilter("Bitcoin+Market+Journal", "Bitcoin Market Journal"),
    SourceFilter("Bitcoin+Magazine", "Bitcoin Magazine"),
    SourceFilter("Bitcoinist", "Bitcoinist"),
    SourceFilter("Bit+News", "Bit News"),
    SourceFilter("Blockchain+News", "Blockchain News"),
    SourceFilter("Blockgeeks", "Blockgeeks"),
    SourceFilter("Blockonomi", "Blockonomi"),
    SourceFilter("Blockworks", "Blockworks"),
    SourceFilter("Bloomberg+Markets+and+Finance", "Bloomberg Markets and Finance"),
    SourceFilter("Bloomberg+Technology", "Bloomberg Technology"),
    SourceFilter("Business+Insider", "Business Insider"),
    SourceFilter("CNBC", "CNBC"),
    SourceFilter("CNBC+Television", "CNBC Television"),
    SourceFilter("CNN", "CNN"),
    SourceFilter("Coinbureau", "Coinbureau"),
    SourceFilter("Coindesk", "Coindesk"),
    SourceFilter("Coindoo", "Coindoo"),
    SourceFilter("Coinfomania", "Coinfomania"),
    SourceFilter("Coingape", "Coingape"),
    SourceFilter("Coin+Idol", "Coin Idol"),
    SourceFilter("CoinMarketCap", "CoinMarketCap"),
    SourceFilter("Coin+News+Asia", "Coin News Asia"),
    SourceFilter("Coinnounce", "Coinnounce"),
    SourceFilter("Coinquora", "Coinquora"),
    SourceFilter("Coinspeaker", "Coinspeaker"),
    SourceFilter("CrowdFundInsider", "CrowdFundInsider"),
    SourceFilter("Crypto+Briefing", "Crypto Briefing"),
    SourceFilter("Crypto+Daily", "Crypto Daily"),
    SourceFilter("Crypto+Economy", "Crypto Economy"),
    SourceFilter("Cryptoknowmics", "Cryptoknowmics"),
    SourceFilter("CryptoNews", "CryptoNews"),
    SourceFilter("Crypto+News", "Crypto News"),
    SourceFilter("CryptoNinjas", "CryptoNinjas"),
    SourceFilter("Cryptopolitan", "Cryptopolitan"),
    SourceFilter("CryptoPotato", "CryptoPotato"),
    SourceFilter("Crypto+Reporter", "Crypto Reporter"),
    SourceFilter("CryptoSlate", "CryptoSlate"),
    SourceFilter("CryptoTicker", "CryptoTicker"),
    SourceFilter("Cryptoverze", "Cryptoverze"),
    SourceFilter("DailyFX", "DailyFX"),
    SourceFilter("DCForecasts", "DCForecasts"),
    SourceFilter("Decrypt", "Decrypt"),
    SourceFilter("EWN", "EWN"),
    SourceFilter("FinanceMagnates", "FinanceMagnates"),
    SourceFilter("Finbold", "Finbold"),
    SourceFilter("Forbes", "Forbes"),
    SourceFilter("Fox+Business", "Fox Business"),
    SourceFilter("Inside+Bitcoins", "Inside Bitcoins"),
    SourceFilter("InvestingCube", "InvestingCube"),
    SourceFilter("Investorplace", "Investorplace"),
    SourceFilter("Koinpost", "Koinpost"),
    SourceFilter("LiveBitcoinNews", "LiveBitcoinNews"),
    SourceFilter("Modern+Consensus", "Modern Consensus"),
    SourceFilter("NewsBTC", "NewsBTC"),
    SourceFilter("Reuters", "Reuters"),
    SourceFilter("The+Block", "The Block"),
    SourceFilter("TCU", "TCU"),
    SourceFilter("The+Cryptonomist", "The Cryptonomist"),
    SourceFilter("The+Currency+Analytics", "The Currency Analytics"),
    SourceFilter("The+Daily+Hodl", "The Daily Hodl"),
    SourceFilter("The+Motley+Fool", "The Motley Fool"),
    SourceFilter("TheNewsCrypto", "TheNewsCrypto"),
    SourceFilter("Tokenpost", "Tokenpost"),
    SourceFilter("Trustnodes", "Trustnodes"),
    SourceFilter("UToday", "UToday"),
    SourceFilter("Yahoo+Finance", "Yahoo Finance"),
    SourceFilter("Zycrypto", "Zycrypto"),
    SourceFilter("8BTC", "8BTC")
)
